language: node_js
node_js:
  - "7"

before_script:
  - git submodule update --init --recursive
  - git submodule foreach "yarn && yarn build"
  - cd core
  - yarn
  - cd node_modules
  - ln -s ../../engine engine
  - cd ..

script:
  - yarn travis
